name: Expo CI-CD

on:
  workflow_dispatch:

jobs:
  Build-for-android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Log in to Expo
        run: eas login -u ${{ secrets.EXPO_CLI_USERNAME }} -p ${{ secrets.EXPO_CLI_PASSWORD }}

      - name: Install Expo GitHub Action
        uses: expo/expo-github-action@v5
        with:
          expo-version: latest
          expo-token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Build Android APK Bundle
        run: eas build --platform android --profile production
