name: feature-ci-test2

on:
  push:
    branches:
      - feature-*
      - sandbox
      - dev
      - stage
      - main

  workflow_dispatch:

jobs:
  if_merged:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/sandbox' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/stage' || github.ref == 'refs/heads/main')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: |
          echo A PR was merged into the main branch.

# jobs:
  # if_closed_pr: 
  #   runs-on: ubuntu-latest
  #   # if: github.event_name == 'pull_request' && github.event.action == 'closed'
  #   if: github.event.pull_request.merged == true
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4.1.2
  #     - run: |
  #         echo A PR was closed.

  Build-for-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2

      - name: Setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run long-running command
        run: |
           # Perform some task that needs to take more than a minute
           echo "Performing time-consuming task..."
        
           # Introduce a sleep command to consume time
           sleep 120  # Sleep for 2 minutes
        
           echo "Task completed."


        
  Build-for-IOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          

      - name: Install dependencies
        run: npm ci

