on:
  # push:
  #    branches:
  #     - feature-*
  #     - sandbox
  #     - dev
  #     - stage
  #     - main
  # pull_request:
  #   types:
  #     - closed
  workflow_dispatch:
# env:
#   expo_auth: ${{ secrets.EXPO_TOKEN }}
jobs:
  if_merged: 
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2
      - run: |
          echo A PR was merged into the main branch.

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.2

    - name: Setup node
      uses: actions/setup-node@v4.0.2
      with:
          node-version: 18.x
          cache: 'npm'
          
    # - name: Setup Android SDK
    #   uses: android-actions/setup-android@v3

    - name: Setup Expo
      uses: expo/expo-github-action@v8
      with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

    - name: Install dependencies
      run: npm ci

    - name: Determine EAS Profile
      id: determine_profile
      run: echo "::set-output name=profile::$(echo $GITHUB_REF | cut -d'/' -f3)"

    - name: Build Android app
      run: eas build --platform android --profile ${{ steps.determine_profile.outputs.profile }} --local --output ${{ github.workspace }}/app-release.apk

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: ${{ github.workspace }}/app-release.apk
